/*
 * board/emcraft/m2s-som/board.c
 *
 * Board specific code the the Emcraft SmartFusion2 system-on-module (SOM).
 *
 * (C) Copyright 2012
 * Emcraft Systems, <www.emcraft.com>
 * Alexander Potashev <aspotashev@emcraft.com>
 * Vladimir Khusainov <vlad@emcraft.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#include <common.h>
#include <m2s.h>
#include <ddr.h>
#include <linux/sizes.h>

DECLARE_GLOBAL_DATA_PTR;

#include "sys_config_mddr_define.h"

volatile struct ddr_regs * const ddr = (void *)0x40020800;

int dram_init (void)
{
	ddr->ddrc.DYN_SOFT_RESET_CR = MDDR_DDRC_DYN_SOFT_RESET_CR;
	ddr->ddrc.RESERVED0 = MDDR_DDRC_RESERVED0;
	ddr->ddrc.DYN_REFRESH_1_CR = MDDR_DDRC_DYN_REFRESH_1_CR;
	ddr->ddrc.DYN_REFRESH_2_CR = MDDR_DDRC_DYN_REFRESH_2_CR;
	ddr->ddrc.DYN_POWERDOWN_CR = MDDR_DDRC_DYN_POWERDOWN_CR;
	ddr->ddrc.DYN_DEBUG_CR = MDDR_DDRC_DYN_DEBUG_CR;
	ddr->ddrc.MODE_CR = MDDR_DDRC_MODE_CR;
	ddr->ddrc.ADDR_MAP_BANK_CR = MDDR_DDRC_ADDR_MAP_BANK_CR;
	ddr->ddrc.ECC_DATA_MASK_CR = MDDR_DDRC_ECC_DATA_MASK_CR;
	ddr->ddrc.ADDR_MAP_COL_1_CR = MDDR_DDRC_ADDR_MAP_COL_1_CR;
	ddr->ddrc.ADDR_MAP_COL_2_CR = MDDR_DDRC_ADDR_MAP_COL_2_CR;
	ddr->ddrc.ADDR_MAP_ROW_1_CR = MDDR_DDRC_ADDR_MAP_ROW_1_CR;
	ddr->ddrc.ADDR_MAP_ROW_2_CR = MDDR_DDRC_ADDR_MAP_ROW_2_CR;
	ddr->ddrc.INIT_1_CR = MDDR_DDRC_INIT_1_CR;
	ddr->ddrc.CKE_RSTN_CYCLES_1_CR = MDDR_DDRC_CKE_RSTN_CYCLES_1_CR;
	ddr->ddrc.CKE_RSTN_CYCLES_2_CR = MDDR_DDRC_CKE_RSTN_CYCLES_2_CR;
	ddr->ddrc.INIT_MR_CR = MDDR_DDRC_INIT_MR_CR;
	ddr->ddrc.INIT_EMR_CR = MDDR_DDRC_INIT_EMR_CR;
	ddr->ddrc.INIT_EMR2_CR = MDDR_DDRC_INIT_EMR2_CR;
	ddr->ddrc.INIT_EMR3_CR = MDDR_DDRC_INIT_EMR3_CR;
	ddr->ddrc.DRAM_BANK_TIMING_PARAM_CR = MDDR_DDRC_DRAM_BANK_TIMING_PARAM_CR;
	ddr->ddrc.DRAM_RD_WR_LATENCY_CR = MDDR_DDRC_DRAM_RD_WR_LATENCY_CR;
	ddr->ddrc.DRAM_RD_WR_PRE_CR = MDDR_DDRC_DRAM_RD_WR_PRE_CR;
	ddr->ddrc.DRAM_MR_TIMING_PARAM_CR = MDDR_DDRC_DRAM_MR_TIMING_PARAM_CR;
	ddr->ddrc.DRAM_RAS_TIMING_CR = MDDR_DDRC_DRAM_RAS_TIMING_CR;
	ddr->ddrc.DRAM_RD_WR_TRNARND_TIME_CR = MDDR_DDRC_DRAM_RD_WR_TRNARND_TIME_CR;
	ddr->ddrc.DRAM_T_PD_CR = MDDR_DDRC_DRAM_T_PD_CR;
	ddr->ddrc.DRAM_BANK_ACT_TIMING_CR = MDDR_DDRC_DRAM_BANK_ACT_TIMING_CR;
	ddr->ddrc.ODT_PARAM_1_CR = MDDR_DDRC_ODT_PARAM_1_CR;
	ddr->ddrc.ODT_PARAM_2_CR = MDDR_DDRC_ODT_PARAM_2_CR;
	ddr->ddrc.ADDR_MAP_COL_3_CR = MDDR_DDRC_ADDR_MAP_COL_3_CR;
	ddr->ddrc.MODE_REG_RD_WR_CR = MDDR_DDRC_MODE_REG_RD_WR_CR;
	ddr->ddrc.MODE_REG_DATA_CR = MDDR_DDRC_MODE_REG_DATA_CR;
	ddr->ddrc.PWR_SAVE_1_CR = MDDR_DDRC_PWR_SAVE_1_CR;
	ddr->ddrc.PWR_SAVE_2_CR = MDDR_DDRC_PWR_SAVE_2_CR;
	ddr->ddrc.ZQ_LONG_TIME_CR = MDDR_DDRC_ZQ_LONG_TIME_CR;
	ddr->ddrc.ZQ_SHORT_TIME_CR = MDDR_DDRC_ZQ_SHORT_TIME_CR;
	ddr->ddrc.ZQ_SHORT_INT_REFRESH_MARGIN_1_CR = MDDR_DDRC_ZQ_SHORT_INT_REFRESH_MARGIN_1_CR;
	ddr->ddrc.ZQ_SHORT_INT_REFRESH_MARGIN_2_CR = MDDR_DDRC_ZQ_SHORT_INT_REFRESH_MARGIN_2_CR;
	ddr->ddrc.PERF_PARAM_1_CR = MDDR_DDRC_PERF_PARAM_1_CR;
	ddr->ddrc.HPR_QUEUE_PARAM_1_CR = MDDR_DDRC_HPR_QUEUE_PARAM_1_CR;
	ddr->ddrc.HPR_QUEUE_PARAM_2_CR = MDDR_DDRC_HPR_QUEUE_PARAM_2_CR;
	ddr->ddrc.LPR_QUEUE_PARAM_1_CR = MDDR_DDRC_LPR_QUEUE_PARAM_1_CR;
	ddr->ddrc.LPR_QUEUE_PARAM_2_CR = MDDR_DDRC_LPR_QUEUE_PARAM_2_CR;
	ddr->ddrc.WR_QUEUE_PARAM_CR = MDDR_DDRC_WR_QUEUE_PARAM_CR;
	ddr->ddrc.PERF_PARAM_2_CR = MDDR_DDRC_PERF_PARAM_2_CR;
	ddr->ddrc.PERF_PARAM_3_CR = MDDR_DDRC_PERF_PARAM_3_CR;
	ddr->ddrc.DFI_RDDATA_EN_CR = MDDR_DDRC_DFI_RDDATA_EN_CR;
	ddr->ddrc.DFI_MIN_CTRLUPD_TIMING_CR = MDDR_DDRC_DFI_MIN_CTRLUPD_TIMING_CR;
	ddr->ddrc.DFI_MAX_CTRLUPD_TIMING_CR = MDDR_DDRC_DFI_MAX_CTRLUPD_TIMING_CR;
	ddr->ddrc.DFI_WR_LVL_CONTROL_1_CR = MDDR_DDRC_DFI_WR_LVL_CONTROL_1_CR;
	ddr->ddrc.DFI_WR_LVL_CONTROL_2_CR = MDDR_DDRC_DFI_WR_LVL_CONTROL_2_CR;
	ddr->ddrc.DFI_RD_LVL_CONTROL_1_CR = MDDR_DDRC_DFI_RD_LVL_CONTROL_1_CR;
	ddr->ddrc.DFI_RD_LVL_CONTROL_2_CR = MDDR_DDRC_DFI_RD_LVL_CONTROL_2_CR;
	ddr->ddrc.DFI_CTRLUPD_TIME_INTERVAL_CR = MDDR_DDRC_DFI_CTRLUPD_TIME_INTERVAL_CR;
	ddr->ddrc.DYN_SOFT_RESET_CR2 = MDDR_DDRC_DYN_SOFT_RESET_ALIAS_CR;
	ddr->ddrc.AXI_FABRIC_PRI_ID_CR = MDDR_DDRC_AXI_FABRIC_PRI_ID_CR;

	ddr->phy.DYN_LOOPBACK_TEST_CR = MDDR_PHY_LOOPBACK_TEST_CR;
	ddr->phy.BOARD_LOOPBACK_CR = MDDR_PHY_BOARD_LOOPBACK_CR;
	ddr->phy.CTRL_SLAVE_RATIO_CR = MDDR_PHY_CTRL_SLAVE_RATIO_CR;
	ddr->phy.CTRL_SLAVE_FORCE_CR = MDDR_PHY_CTRL_SLAVE_FORCE_CR;
	ddr->phy.CTRL_SLAVE_DELAY_CR = MDDR_PHY_CTRL_SLAVE_DELAY_CR;
	ddr->phy.DATA_SLICE_IN_USE_CR = MDDR_PHY_DATA_SLICE_IN_USE_CR;
	ddr->phy.LVL_NUM_OF_DQ0_CR = MDDR_PHY_LVL_NUM_OF_DQ0_CR;
	ddr->phy.DQ_OFFSET_1_CR = MDDR_PHY_DQ_OFFSET_1_CR;
	ddr->phy.DQ_OFFSET_2_CR = MDDR_PHY_DQ_OFFSET_2_CR;
	ddr->phy.DQ_OFFSET_3_CR = MDDR_PHY_DQ_OFFSET_3_CR;
	ddr->phy.DIS_CALIB_RST_CR = MDDR_PHY_DIS_CALIB_RST_CR;
	ddr->phy.DLL_LOCK_DIFF_CR = MDDR_PHY_DLL_LOCK_DIFF_CR;
	ddr->phy.FIFO_WE_IN_DELAY_1_CR = MDDR_PHY_FIFO_WE_IN_DELAY_1_CR;
	ddr->phy.FIFO_WE_IN_DELAY_2_CR = MDDR_PHY_FIFO_WE_IN_DELAY_2_CR;
	ddr->phy.FIFO_WE_IN_DELAY_3_CR = MDDR_PHY_FIFO_WE_IN_DELAY_3_CR;
	ddr->phy.FIFO_WE_IN_FORCE_CR = MDDR_PHY_FIFO_WE_IN_FORCE_CR;
	ddr->phy.FIFO_WE_SLAVE_RATIO_1_CR = MDDR_PHY_FIFO_WE_SLAVE_RATIO_1_CR;
	ddr->phy.FIFO_WE_SLAVE_RATIO_2_CR = MDDR_PHY_FIFO_WE_SLAVE_RATIO_2_CR;
	ddr->phy.FIFO_WE_SLAVE_RATIO_3_CR = MDDR_PHY_FIFO_WE_SLAVE_RATIO_3_CR;
	ddr->phy.FIFO_WE_SLAVE_RATIO_4_CR = MDDR_PHY_FIFO_WE_SLAVE_RATIO_4_CR;
	ddr->phy.GATELVL_INIT_MODE_CR = MDDR_PHY_GATELVL_INIT_MODE_CR;
	ddr->phy.GATELVL_INIT_RATIO_1_CR = MDDR_PHY_GATELVL_INIT_RATIO_1_CR;
	ddr->phy.GATELVL_INIT_RATIO_2_CR = MDDR_PHY_GATELVL_INIT_RATIO_2_CR;
	ddr->phy.GATELVL_INIT_RATIO_3_CR = MDDR_PHY_GATELVL_INIT_RATIO_3_CR;
	ddr->phy.GATELVL_INIT_RATIO_4_CR = MDDR_PHY_GATELVL_INIT_RATIO_4_CR;
	ddr->phy.LOCAL_ODT_CR = MDDR_PHY_LOCAL_ODT_CR;
	ddr->phy.INVERT_CLKOUT_CR = MDDR_PHY_INVERT_CLKOUT_CR;
	ddr->phy.RD_DQS_SLAVE_DELAY_1_CR = MDDR_PHY_RD_DQS_SLAVE_DELAY_1_CR;
	ddr->phy.RD_DQS_SLAVE_DELAY_2_CR = MDDR_PHY_RD_DQS_SLAVE_DELAY_2_CR;
	ddr->phy.RD_DQS_SLAVE_DELAY_3_CR = MDDR_PHY_RD_DQS_SLAVE_DELAY_3_CR;
	ddr->phy.RD_DQS_SLAVE_FORCE_CR = MDDR_PHY_RD_DQS_SLAVE_FORCE_CR;
	ddr->phy.RD_DQS_SLAVE_RATIO_1_CR = MDDR_PHY_RD_DQS_SLAVE_RATIO_1_CR;
	ddr->phy.RD_DQS_SLAVE_RATIO_2_CR = MDDR_PHY_RD_DQS_SLAVE_RATIO_2_CR;
	ddr->phy.RD_DQS_SLAVE_RATIO_3_CR = MDDR_PHY_RD_DQS_SLAVE_RATIO_3_CR;
	ddr->phy.RD_DQS_SLAVE_RATIO_4_CR = MDDR_PHY_RD_DQS_SLAVE_RATIO_4_CR;
	ddr->phy.WR_DQS_SLAVE_DELAY_1_CR = MDDR_PHY_WR_DQS_SLAVE_DELAY_1_CR;
	ddr->phy.WR_DQS_SLAVE_DELAY_2_CR = MDDR_PHY_WR_DQS_SLAVE_DELAY_2_CR;
	ddr->phy.WR_DQS_SLAVE_DELAY_3_CR = MDDR_PHY_WR_DQS_SLAVE_DELAY_3_CR;
	ddr->phy.WR_DQS_SLAVE_FORCE_CR = MDDR_PHY_WR_DQS_SLAVE_FORCE_CR;
	ddr->phy.WR_DQS_SLAVE_RATIO_1_CR = MDDR_PHY_WR_DQS_SLAVE_RATIO_1_CR;
	ddr->phy.WR_DQS_SLAVE_RATIO_2_CR = MDDR_PHY_WR_DQS_SLAVE_RATIO_2_CR;
	ddr->phy.WR_DQS_SLAVE_RATIO_3_CR = MDDR_PHY_WR_DQS_SLAVE_RATIO_3_CR;
	ddr->phy.WR_DQS_SLAVE_RATIO_4_CR = MDDR_PHY_WR_DQS_SLAVE_RATIO_4_CR;
	ddr->phy.WR_DATA_SLAVE_DELAY_1_CR = MDDR_PHY_WR_DATA_SLAVE_DELAY_1_CR;
	ddr->phy.WR_DATA_SLAVE_DELAY_2_CR = MDDR_PHY_WR_DATA_SLAVE_DELAY_2_CR;
	ddr->phy.WR_DATA_SLAVE_DELAY_3_CR = MDDR_PHY_WR_DATA_SLAVE_DELAY_3_CR;
	ddr->phy.WR_DATA_SLAVE_FORCE_CR = MDDR_PHY_WR_DATA_SLAVE_FORCE_CR;
	ddr->phy.WR_DATA_SLAVE_RATIO_1_CR = MDDR_PHY_WR_DATA_SLAVE_RATIO_1_CR;
	ddr->phy.WR_DATA_SLAVE_RATIO_2_CR = MDDR_PHY_WR_DATA_SLAVE_RATIO_2_CR;
	ddr->phy.WR_DATA_SLAVE_RATIO_3_CR = MDDR_PHY_WR_DATA_SLAVE_RATIO_3_CR;
	ddr->phy.WR_DATA_SLAVE_RATIO_4_CR = MDDR_PHY_WR_DATA_SLAVE_RATIO_4_CR;
	ddr->phy.WRLVL_INIT_MODE_CR = MDDR_PHY_WRLVL_INIT_MODE_CR;
	ddr->phy.WRLVL_INIT_RATIO_1_CR = MDDR_PHY_WRLVL_INIT_RATIO_1_CR;
	ddr->phy.WRLVL_INIT_RATIO_2_CR = MDDR_PHY_WRLVL_INIT_RATIO_2_CR;
	ddr->phy.WRLVL_INIT_RATIO_3_CR = MDDR_PHY_WRLVL_INIT_RATIO_3_CR;
	ddr->phy.WRLVL_INIT_RATIO_4_CR = MDDR_PHY_WRLVL_INIT_RATIO_4_CR;
	ddr->phy.WR_RD_RL_CR = MDDR_PHY_WR_RD_RL_CR;
	ddr->phy.RDC_FIFO_RST_ERRCNTCLR_CR = MDDR_PHY_RDC_FIFO_RST_ERR_CNT_CLR_CR;
	ddr->phy.RDC_WE_TO_RE_DELAY_CR = MDDR_PHY_RDC_WE_TO_RE_DELAY_CR;
	ddr->phy.USE_FIXED_RE_CR = MDDR_PHY_USE_FIXED_RE_CR;
	ddr->phy.USE_RANK0_DELAYS_CR = MDDR_PHY_USE_RANK0_DELAYS_CR;
	ddr->phy.USE_LVL_TRNG_LEVEL_CR = MDDR_PHY_USE_LVL_TRNG_LEVEL_CR;
	ddr->phy.DYN_CONFIG_CR = MDDR_PHY_DYN_CONFIG_CR;
	ddr->phy.RD_WR_GATE_LVL_CR = MDDR_PHY_RD_WR_GATE_LVL_CR;
	ddr->phy.DYN_RESET_CR = MDDR_PHY_DYN_RESET_CR;

	ddr->fic.NB_ADDR_CR = MDDR_DDR_FIC_NB_ADDR_CR;
	ddr->fic.NBRWB_SIZE_CR = MDDR_DDR_FIC_NBRWB_SIZE_CR;
	ddr->fic.WB_TIMEOUT_CR = MDDR_DDR_FIC_WB_TIMEOUT_CR;
	ddr->fic.HPD_SW_RW_EN_CR = MDDR_DDR_FIC_HPD_SW_RW_EN_CR;
	ddr->fic.HPD_SW_RW_INVAL_CR = MDDR_DDR_FIC_HPD_SW_RW_INVAL_CR;
	ddr->fic.SW_WR_ERCLR_CR = MDDR_DDR_FIC_SW_WR_ERCLR_CR;
	ddr->fic.ERR_INT_ENABLE_CR = MDDR_DDR_FIC_ERR_INT_ENABLE_CR;
	ddr->fic.NUM_AHB_MASTERS_CR = MDDR_DDR_FIC_NUM_AHB_MASTERS_CR;
	ddr->fic.LOCK_TIMEOUTVAL_1_CR = MDDR_DDR_FIC_LOCK_TIMEOUTVAL_1_CR;
	ddr->fic.LOCK_TIMEOUTVAL_2_CR = MDDR_DDR_FIC_LOCK_TIMEOUTVAL_2_CR;
	ddr->fic.LOCK_TIMEOUT_EN_CR = MDDR_DDR_FIC_LOCK_TIMEOUT_EN_CR;

	ddr->ddrc.DYN_SOFT_RESET_CR = 1;
	while(!ddr->ddrc.SR);

	gd->ram_base = CONFIG_SYS_SDRAM_BASE;
	gd->ram_size = get_ram_size((void *)CONFIG_SYS_SDRAM_BASE, SZ_1G);

	return 0;
}
